name: momento_las_palmas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # utils
  logger: ^2.5.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  freezed_annotation: ^2.4.4
  share_plus: ^10.1.4
  permission_handler: ^10.4.0
  # maps
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # state management
  flutter_bloc: ^9.0.0

  # local data saving
  shared_preferences: ^2.5.2

  # routing
  go_router: ^14.8.0

  flutter_native_splash: ^2.4.5
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.1.7
  onesignal_flutter: ^5.1.2
  appsflyer_sdk: ^6.15.2
  http: ^1.2.1
  advertising_id: ^2.0.0
  flutter_inappwebview: ^6.1.5
  image_picker: ^0.8.7+4
  external_app_launcher: ^4.0.3
  app_tracking_transparency: ^2.0.6+1
  device_info_plus: ^11.4.0


flutter_native_splash:
  color: '#ffffff'
  image: assets/images/l1.png
  ios_content_mode: scaleAspectFill

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800

  assets:
    - assets/images/
    - assets/images/splash_icons/
    - assets/images/onboard_images/
    - assets/images/spin_images/
    - assets/local_data/
    - assets/images/bg.png
    - assets/images/l1.png
